# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('grad_date', models.DateTimeField(verbose_name='Graduation Date')),
                ('major', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=50)),
                ('resume_url', models.CharField(max_length=50)),
            ],
        ),
    ]
